### ISSUE TITLE
EQUIP_PARAM_GEM_ST.xml entryName fix

### ISSUE THREAD

**Issue by SweetInk** [vawser/Yapped-Rune-Bear#14]
https://github.com/vawser/Yapped-Rune-Bear/blob/74f3598d0f792caecbda6d8b0e1b6f5bdd3d284a/res/GR/Layouts/EQUIP_PARAM_GEM_ST.xml#L63

It should be Icon ID

**Comment by vawser** [comment]
Has been fixed in the latest commit.
