### ISSUE TITLE
Weapon Effect wrong value?!

### ISSUE THREAD

**Issue by Sonatine1** [vawser/Yapped-Rune-Bear#15]
Hey!

In "SpEffectParam" under 1927 (Dragon Communion Seal) the "Weapon Effect 1" under s8 says "Enhance Frenzied Flame Incantations", but shouldn't it be "Enhance Dragon Communion Incantations"? The Frenzied Flame Seal under 1928 has nothing under "Weapon Effect 1", while all the other Seals have fitting descriptions. Although I think in a previous version it was correct already afaik, since I already worked with some effects.

Best regards
Sona

**Comment by vawser** [comment]
I've updated the enum that labels this in the latest commit, and I remember correcting the Frenzied Flame one to Dragon Communion, so this is fixed now.
