### ISSUE TITLE
NpcParam-> Row ID: 21300000 Name: Malenia. Is actually Morgot?

### ISSUE THREAD

**Issue by BurgersMcFly** [vawser/Yapped-Rune-Bear#17]
NpcParam-> Row ID: 21300000 Name: Malenia. Is actually Morgot? 

Sorry no idea how github works yet D:

![Yapped_WdLkMrZLXE](https://user-images.githubusercontent.com/26502050/159941081-2bc05a58-f4ef-418c-ae0f-ad883926ffb8.png)
![Yapped_3kWxbF9T0s](https://user-images.githubusercontent.com/26502050/159941087-91776eaa-7ddc-4b54-9200-b18b3e3cdabc.png)
![eldenring_97HtpMsi5R](https://user-images.githubusercontent.com/26502050/159941187-c0476e65-4d7c-4941-a90f-ac90968d781d.jpg)

**Comment by Clifford949** [comment]
have you tried the other ID's for Malenia? Try importing the names again, it might work.

**Comment by BurgersMcFly** [comment]
Oh new Yapped update! Lemme try that again.

**Comment by BurgersMcFly** [comment]
Nope, still Morgot. 

What 1.06 did tho is break the import function for me lol.

**Comment by vawser** [comment]
Fixed
