### ISSUE TITLE
It is recommended that you use a comma as the delimiter for csv files

### ISSUE THREAD

**Issue by SweetInk** [vawser/Yapped-Rune-Bear#19]
If you use a semicolon as a delimiter, the csv file will not be displayed correctly in Excel

**Comment by vawser** [comment]
You can change this in the Yapped settings menu. Although row names use commas, so semi-colons are less likely to cause issues there. You can always find and replace them after exporting too.

**Comment by bilbop** [comment]
or you can do what i do...
i have own set of data, USING , as separator = default
of couse all texts i replaced ", " with " - " so data are still intact.
