### ISSUE TITLE
Can't find "Mass Export Data"

### ISSUE THREAD

**Issue by Turrabo** [vawser/Yapped-Rune-Bear#20]
Sorry for the inane question, but I'm trying to follow the instructions for [Updating a Mod](https://github.com/vawser/Yapped-Rune-Bear#updating-a-mod) and I can't find the "Mass Export Data" button anywhere in the app?

I'm also not sure where the exported files get dumped. For example when clicking Export Data for current param rows. Any tips appreciated.

**Comment by vawser** [comment]
You need to download the latest release to have it. The exported files will be found in <Yapped exe directory>/res/GR/Data/, if you set a Project Name, the directory will be <Yapped exe directory>/res/GR/Data/<project name>

**Comment by Turrabo** [comment]
Didn't know you guys were committing so frequently. Awesome work 🙂
