### ISSUE TITLE
Where can I see the damage and speed of ash of war?

### ISSUE THREAD

**Issue by vnvvnvn** [vawser/Yapped-Rune-Bear#21]
Where can I see the damage and speed of ash of war?

SwordArtsParam only has limited data.

I'm looking for BLOODY SLASH, HOARFROST STOMP data.

**Comment by DemianDancer** [comment]
Yeah, you are right. Some parameters should be found on the others.
For example, if you want to change the damage of hoarfrost.
To check Para 'Atk_Param_PC' row number '30300862 / 30300863' 
Some effects of ashes like buff also are located Para name 'SpEffectPara'

**Comment by pendvlvm** [comment]
> Yeah, you are right. Some parameters should be found on the others. For example, if you want to change the damage of hoarfrost. To check Para 'Atk_Param_PC' row number '30300862 / 30300863' Some effects of ashes like buff also are located Para name 'SpEffectPara'

Wow, how do you know this? Can you tell me how can I find "Gravitas" skill in the 'Atk_Param_PC'?

**Comment by DemianDancer** [comment]
@pendvlvm 

They split skill into 3 stage by distance.
Atk_Param_PC : 30300850 ~ 30300852  'Gravitas'
Bullet : 2190 ~ 2192 'Gravitas' - Initial hit range.
