### ISSUE TITLE
My yapped rune it's confusing my files with sekiro and i can't put my mods on elden ring

### ISSUE THREAD

**Issue by YDdraigG** [vawser/Yapped-Rune-Bear#23]
![image](https://user-images.githubusercontent.com/102542677/160445632-3e0e5479-439e-4734-80f6-cf781b8a0e0e.png)

**Comment by McDikkens** [comment]
Ayo same, have you found a solution yet?

**Comment by McDikkens** [comment]
I found the solution: Open up yapped, then go files to open; choose the regulation file. Then make sure to import name. That should be it.

**Comment by YDdraigG** [comment]
where do i find the regulation files? why when I click on Show Regulation File nothing happens

**Comment by YDdraigG** [comment]
nvm i got thx
