### ISSUE TITLE
What to do if Yapped is updated

### ISSUE THREAD

**Issue by deltaofurs** [vawser/Yapped-Rune-Bear#24]
If I have been playing around with .bin in an older version of Yapped, what should I do if I install a newer version of Yapped?
Do I just open it in the new yapped and extract the CSV of the mod and install it?

**Comment by vawser** [comment]
You can just open it with the updated Yapped.

**Comment by deltaofurs** [comment]
I'm making a mod, but with each Yapped version upgrade, do I have to deal with something on the side of the mod I'm making? Just like the game itself app.
