### ISSUE TITLE
So I download the lasted version of Yapped Rune Bear but I couldn't open it.

### ISSUE THREAD

**Issue by Sattharos** [vawser/Yapped-Rune-Bear#27]
Can someone help me with this, I downloaded the lasted version 1.08 and since didn't see any instruction so i extract it on desktop. This happened
![image](https://user-images.githubusercontent.com/102810876/161275434-9fb79688-7264-4bb2-8613-c3fea28c8570.png)
I can't find solotion anywhere, someone said change the inside to Elden ring. I did that but nothing happend, i did everything i could still can't fix this. Funny enough i didn't even own Sekiro.

**Comment by BurgersMcFly** [comment]
File->Open.
Make sure to pic Elden Ring from the top down menu in there as well.

**Comment by Sattharos** [comment]
> File->Open. Make sure to pic Elden Ring from the top down menu in there as well.

I did that and it seem to solve the Sekiro issue but this happened 
![image](https://user-images.githubusercontent.com/102810876/161372811-91c24974-fe0a-4478-8794-f62f0b43c17a.png)
Thank for the reply

**Comment by Adri29492** [comment]
I have the same problem, anyone found a solution?

**Comment by Sattharos** [comment]
> I have the same problem, anyone found a solution?

haven't find any yet since posted this. 1.09 version still have this problem. If anyone found the solution please tell me ;w;

**Comment by Sattharos** [comment]
> I have the same problem, anyone found a solution?

I found the solotion on Nexusmods. I guess im an idiot trying to open Data0.bdt but actually you have to open regulation.bin
"once you download Yapped , unzip it you'll see file name Yapped with brownbox icon.
Double click on it then program open -> file -> change from sekiro to elden ring (under export) then open your Regulation file in C:\Program Files (x86)\Steam\Steamapps\common\ELDEN RING\Game"
you have to open Yapped  first , if you click on your Regulation file directly it won't work
you have to double click Yapped app to open it from its own folder first"

**Comment by Adri29492** [comment]
That does work! guess I'm an idiot too. It pointed directly to Data0 and if I recall correctly in another souls game it was Data0 so I just went with it. Thanks!

**Comment by YoussefJarray** [comment]
i could not get this to work whatsoever, still facing the same error

**Comment by eelonmusk03** [comment]
tried opening the regulation.bin file from within yapped (first time using this) and got this 

<img width="535" height="372" alt="Image" src="https://github.com/user-attachments/assets/2ff503e7-19f5-4ed0-ad03-251e477153bc" />
