### ISSUE TITLE
[Feature requests] Save file sl2 Support for ELDEN RING 

### ISSUE THREAD

**Issue by hruban** [vawser/Yapped-Rune-Bear#29]

**Comment by Mikomaticks** [comment]
I save it but it reverts back to dark souls 3 every time I open it. And even then selecting elden ring has an error of parambnb and the contents of yapped don't show up. It really sucks cause I have a few csv's ready to go, but I guess I'm just fucked.

**Comment by Mikomaticks** [comment]
I'm also on windows 11, and maybe that's why...?

**Comment by vawser** [comment]
Saves are outside the purview of Yapped and not something I aim to support editing.
