### ISSUE TITLE
Modified values in Elden Ring 1.03.3 do not save

### ISSUE THREAD

**Issue by nickvoegeli** [vawser/Yapped-Rune-Bear#31]
Steps to reproduce:

1. Open Yapped and select Elden Ring
2. Modify a value.  I'm trying ClearCountCorrectParam -> NG+0 -> Rune Multiplier
3. Save
4. Close Yapped
5. Re-open Yapped and look at the value you modified

Expected behavior: modified value appears
Actual behavior: default value appears

**Comment by DDDayln** [comment]
I was having a similar issue, I took my regulation.bin file out of my steamapps/common/EldenRing/Game folder and I was able to edit it that way and have the changes carry over to the game. I don't know if it had something to do with folder permissions or what but that seems to have solved my issue for now.

**Comment by imakunee** [comment]
My changes are saving in yapped, including when restarting the program and reloading, but they aren't represented in the game. Testing by changing the recipe for bone darts to make 6 but it stays making 5 in spite of the regulation.bin being different.

**Comment by nickvoegeli** [comment]
Following the lead about permissions, I tried running yapped as administrator and modifying the file in place in the Elden Ring game folder.  Same result: changes appeared to save, but when I closed and re-opened yapped the changes were gone.

Next, I tried moving the `regulation.bin` file out of the game folder and onto my desktop.  Same result as above.

Then, I tried modifying `regulation.bin` on the desktop as an administrator.  Same result as above.

I also verified that the `regulation.bin` file has permissions set to Full Control for system, administrators, and my own account.

**Comment by imakunee** [comment]
I moved my regulation.bin to a different folder then had the game redownload the regulation.bin via verify file integrity. Then, using the 1.10 yapped I've imported my old data into the newly downloaded bin and the changes began to show up in game again.

**Comment by HyperX239** [comment]
I have a similar issue, did the same steps too, no positives results, it pop-up an error message to me sometimes, but not anymore, now it only do a window sound of something not working.

**Comment by nickvoegeli** [comment]
I tried @imakunee 's solution above with no luck.  I deleted `regulation.bin`, verified file integrity through Steam, then downloaded the latest yapped release.  I opened the new `regulation.bin` and modified the same variable (`ClearCountParams` -> `0` -> `RuneMultiplier` then saved, and when I closed and re-opened yapped the value had reset to default.

**Comment by nickvoegeli** [comment]
Good news!  I'm dumb.  I was having two problems:

1. You have to hit enter after editing a value in yapped or it won't save
2. Even after finding this problem, my changes weren't showing up in game. I deleted `regulation.bin` again and validated local file integrity through Steam to re-download, then made my changes again (and hit enter this time).

This totally worked and my changes are showing up in game.  Thanks @imakunee !
