### ISSUE TITLE
LoadBalancerNewDrawDistScaleParam_win64 typo?

### ISSUE THREAD

**Issue by BurgersMcFly** [vawser/Yapped-Rune-Bear#33]
Second Shadow Draw Distance Scale Start should be Shadow Draw Distance Scale End?

![Yapped_fBfAf9QM0j](https://user-images.githubusercontent.com/26502050/161954385-531675bb-477e-4241-bb62-3a305695ad06.png)

**Comment by vawser** [comment]
Fixed
