### ISSUE TITLE
Bug Report? BuddyStoneParam Row Numbers changing after importing .csv

### ISSUE THREAD

**Issue by BurgersMcFly** [vawser/Yapped-Rune-Bear#36]
How to replicate:

Have an unmodified regulation.bin
Launch Yapped and open that regulation.bin file.
Go to BuddyStoneParam and do Export Data.
Then do Import Data.
Row numbers go bananas?
Stuff on the right panel go bananas as well?

Row Numbers before Importing:
![Yapped_niH7ntsFP9](https://user-images.githubusercontent.com/26502050/162924091-f3a2b51a-c401-4cd1-ac93-eab0b1478a9c.png)

Row Numbers after Importing:
![Yapped_2ggJBwaxua](https://user-images.githubusercontent.com/26502050/162924199-185e5ff2-f27d-4401-a2fc-5cf9eabb2927.png)

**Comment by vawser** [comment]
Looks fine to me. 

The vanilla params aren't necessarily sorted. When you save the rows are sorted, which is what you are seeing change. 

The field values are fine too, the map event flags are just large: 1054560100 is referring to m60_54_56

**Comment by BurgersMcFly** [comment]
K, thanks for the explanation mate.
