### ISSUE TITLE
Not spawning NPCs invaders or summon NPCs

### ISSUE THREAD

**Issue by Adri29492** [vawser/Yapped-Rune-Bear#39]
After editing the regulation.bin I can't summon (not seen summon sign) or be invaded by NPCs. I don't mean players, I play offline.
Could it be due to 1.03.3 update? I've only edited weapons, armors and talismans. Giving greatbows more range, tree sentinel armor more poise or giving moon of nokstella FP regen.

**Comment by SebyS7** [comment]
there was a similar error in the past reported, and there is a fix for this. look at the closed issues like "https://github.com/vawser/Yapped-Rune-Bear/issues/37" or "https://github.com/vawser/Yapped-Rune-Bear/issues/34".

This will help you out i guess.

**Comment by Adri29492** [comment]
That worked, thanks. Sorry for reporting the same problem I'm new to github, I'm still finding my way around.
