### ISSUE TITLE
Naming style of fields

### ISSUE THREAD

**Issue by wswslzp** [vawser/Yapped-Rune-Bear#41]
In the latest version, the naming style is more difficult to read than in the old version. Could this new style restore back to old style?

![image](https://user-images.githubusercontent.com/30322341/164585969-68c0633c-3c41-47b9-8d12-886b1a6d2886.png)

compared to 

![image](https://user-images.githubusercontent.com/30322341/164586082-c310ba0d-4b27-497c-9a94-ecd70796a437.png)

**Comment by vawser** [comment]
There is an option to switch between the "true" field names and my naming. It is under "View", called "Toggle Field Name Type". 

However it is incomplete at the moment since I need to integrate the old names into the Paramdex xml files. The next update will
 restore it fully.

**Comment by wswslzp** [comment]
Thanks!
