### ISSUE TITLE
Dropdowns No Longer Available

### ISSUE THREAD

**Issue by coldpaintedash** [vawser/Yapped-Rune-Bear#47]
Version 2.1.0, seemingly at random all the dropdowns are no longer present and will not reappear even after editing the "show enum" settings.

**Comment by mindstrip** [comment]
I was having the same issue, but resolved it by turning off "Param Difference mode coloring":

**File Data** > **Toggle Param Difference Mode**
Lastly, I selected another Param or Row in order to see the changes ("refreshing the page", kinda deal).

**Comment by vawser** [comment]
mindstrip is correct, Param Difference mode disables the enum selection when active so you can see the difference coloring.
