### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by IchijyoRaku** [vawser/Yapped-Rune-Bear#52]
Sorry to bother you and take up your precious time to read it. Could you add support for Chinese name when exporting data? When I use Chinese name, the exported Chinese name will become garbled. For a few data, I can use English, but when looking up a large amount of data, the Chinese name is of great significance to me.As for the name display of ref ID, Dark Souls ParamStudio directly displays its name below. I think it is more intuitive and efficient than the current mode of hovering the mouse to display description.I think it can be used as an improvement point.I can only provide a donation of about $20 to support your work in yapped.Of course, you can ignore everything I say.Because maybe my request and reward are unreasonable.Thank you very much. :)

**Comment by Hiei-YYH** [comment]
talking about requests, something that would be useful also, export specific lines and import these... because usually when trying to mod a csv file you lose all other changes you made it. Dunno if there's a way to do that, if has please just explain.
