### ISSUE TITLE
why the total modification?

### ISSUE THREAD

**Issue by Hiei-YYH** [vawser/Yapped-Rune-Bear#55]
the older version for example had a droplist in state info (just an example) where it says what are the conditions etc... now it's just a flat text box and we have to just guess? i see no advantage in using this new 2.0 version. I can look in another site? yes, but what a waste of time since it was so well done before... just my 2 cents. Thanks for the application anyways.

**Comment by vawser** [comment]
The combo boxes still exist, they can just be toggled on and off in the settings.

**Comment by Hiei-YYH** [comment]
> The combo boxes still exist, they can just be toggled on and off in the settings.

well, i looked and didn't found it... can you elaborate please?

the unmarked checkboxes in settings are:
Export Unique Values Only
Supress Confirmation Messages
Automatically open output files
Save without encryption


and that's it.

**Comment by Hiei-YYH** [comment]
forget my comment, i downloaded the new 2.14 version and it is back, i was using the 2.0 that was released before... didn't saw you updated, thank you.
