### ISSUE TITLE
Finding out what the unknown "Unk" values mean?

### ISSUE THREAD

**Issue by Sonatine1** [vawser/Yapped-Rune-Bear#6]
Hey!

First of all: Great tool! :)

Is there a way to find out what f.e. "Unk94" in the EquipWeaponParam when selecting a weapon means? Would be really helpful to know these values and what they do.

Best regards
Sona

**Comment by Sonatine1** [comment]
Sorry for the naive post. After spending two days with the tool I get used to trying out to "crack" the specific values, so I see why they are not in yet.

Is there an official Discord where you guys post? I'm on Hexington already for some days now.

**Comment by vawser** [comment]
Unk fields are fields that I do not know of the function yet. It is a long process to find out what all of them are, so if you discover any that are not already done, post them here and I'll add them in.

**Comment by Sonatine1** [comment]
Okay, I'll do that. :)
