### ISSUE TITLE
Few instances of incorrect names in EquipParamWeapon paramdex

### ISSUE THREAD

**Issue by Phil25** [vawser/Yapped-Rune-Bear#61]
There are 3 instances that don't match with item-msgbnd:
- `Onyx Lord's Sword` instead of `Alabaster Lord's Sword` (matched by IDs; there is a `Onyx Lord's Greatsword`, but it's a different weapon)
- `Great epee` instead of `Great Epee`
- `Sacred Mohgwyn's Spear` instead of `Mohgwyn's Sacred Spear`

Some names are missing special symbols but that's not as important:
- `Misericorde` -> `Miséricorde`
- `Great Epee` -> `Great Épée`
- `Varre's Bouquet` -> `Varré's Bouquet`

**Comment by vawser** [comment]
Fixed the mismatched names for the Stock Name import. The special symbols have been skipped since they can cause issues due to text encoding.

**Comment by Phil25** [comment]
This has been fixed in [2.14.1](https://github.com/vawser/Yapped-Rune-Bear/commit/cdda5b8cc26d3054a98842ebcfd2e3cfe6b4bb60)
