### ISSUE TITLE
Can't import data

### ISSUE THREAD

**Issue by NickEtlis** [vawser/Yapped-Rune-Bear#8]
Getting error when trying to import .csv files even if I export them before by myself

**Comment by Spark-NV** [comment]
Saying "I got an error" is completely and utterly useless. if you want to report a bug, atleast give some info. Version of program, version of game, what you did exactly, what the error message says etc...

**Comment by bilbop** [comment]
i tested...
all next releases (1.02 and later) DONT WORK IMPORT FOR ALL FIELDS)))
only main base version is functional.
later are good just for reference of row values and names))

**Comment by YakoKuna** [comment]
Is this happening to a clean version of an updated regulation.bin file (1.03.2 with not modifications done to it)?
Tried exporting data from a clean version of an updated regulation.bin file (1.03.2 with not modifications done to it) and importing it back?

**Comment by bilbop** [comment]
> Is this happening to a clean version of an updated regulation.bin file (1.03.2 with no modifications done to it)? Tried exporting unmodified data from a clean version of an updated regulation.bin file (1.03.2 with no modifications done to it) and importing it back to it?

it happens to any version with some categories...
sw by itself correctly should import all separated by , no matter whats headlines...
problem is, only base version imports almost all, no matter clear or updated file...

**Comment by Clifford949** [comment]
The newest version (1.06) fixed it for me. Thank you for this

**Comment by bilbop** [comment]
> The newest version (1.06) fixed it for me. Thank you for this

i must try too if this version fixes import unability with errors))

**Comment by bilbop** [comment]
> > The newest version (1.06) fixed it for me. Thank you for this
> 
> i must try too if this version fixes import unability with errors))

seems still happens issues, should i provide link for source files to test??
